### ISSUE TITLE
Remis master To-do list

### ISSUE THREAD

**Issue by remiolsen** [remiolsen/nf-core-neutronstar#1]
For transparency, here's my "design document"

------
**Main requirements**
- [x] Nextflow? yes
- [x] Supernova running in $SNIC_TMP (Irma compatible?)
    - [x] 1.20 compatible — multiple input parameter assemblies
    - [x] ~Use nextflow publishdata in stead of rsync~ Couldn't get this to work. Including Rsync with the image
    - [x] Make a this optional
- [x] Rsync supernova assembly back to workdir
- [x] supernova mkoutput - pseudohap, megabubbles
    - [x] gunzip
    - [x] parameter of additional outputs — always output .phased.fasta
    - [x] parameter for minimum length
- [x] QUAST
    - [x] make it run on Irma
- [x] BUSCO
    - [x] UPPMAX — beforeScript
- [x] MultiQC
   - [x] Needs testing
- [x] support for —no-preflight flag
- [ ] Documentation
    - [x] Readme.md
- [x] dump software versions & commands that were run
- [x] Send mail when done pipeline is finished
- [x] Clean up and generalize the configs
     - [x] Common HPC config
     - [x] Common Uppmax config
     - [x] Make a general local run config

**Docker / Singularity**
- [x] Supernova (copyright issues?)
- [x] Quast
- [x] BUSCO
- [x] ~Script for automatic singularity/docker download / installation~

**NX script**
- [ ] input configuration:
    - [x] id
         - [x] fastqs
         - [x] sample
         - [x] maxreads
         - [x] bcfrac
    - [x] genomesize
- [x] memory parameter
- [x] cpu parameter
    - [x] see RNAseq pipeline
- [x] make Longranger / fastqc optional
**Input_validation**
   - [x] id — only numbers, letters, dash, and underscore allowed
   - [ ] ~bcfrac (0,1)~
   - [ ] ~maxreads - num~

**MultiQC**
- [x] Fix when having empty molecule.yaml files
- [x] Does having “ASSEMBLER_CS” folders break multiqc? **No**
- [x] Fix QUAST module. It breaks when running with -s option **someone else did it**

**Could haves**
- [ ] Tigmint evaluation
- [ ] Delivery template mail / output folder structure
- [ ] BWA align
    - [ ] picard-tools
    - [ ] remove dups
    - [ ] collectinsertsize
- [ ] qaTools-singularity
- [ ] FRC-singularity
- [x] BUSCOv2 datasets in config
    - [x] auto-script to download datasets
